function [ys_, params, info] = credit_RBC_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    pi=1.004;
    ys_(1)=1/params(2);
    r=pi*ys_(1);
    ys_(5)=0.3333333333333333;
    ys_(14)=1;
    ys_(12)=1-params(1)/params(2);
    ys_(8)=ys_(5)*(((1-ys_(12)*params(10)/ys_(1))/params(1)-(1-params(3)))/params(4))^(1/(params(4)-1));
    ys_(7)=ys_(8)^params(4)*ys_(5)^(1-params(4));
    ys_(9)=params(3)*ys_(8);
    ys_(6)=(1-params(4))*ys_(7)/ys_(5)/(1+ys_(12)*params(9));
    ys_(10)=params(10)*ys_(8)/ys_(1)-ys_(5)*params(9)*ys_(6);
    ys_(3)=ys_(7)+ys_(8)*(-params(3))-ys_(5)*ys_(6)+ys_(10)*(1-ys_(1));
    ys_(4)=ys_(7)*(1-params(8))-ys_(9)-ys_(3);
    ys_(2)=ys_(3)+ys_(4);
    ys_(11)=(ys_(3)-ys_(3)*params(12))^(-params(5));
    ys_(13)=(ys_(4)-ys_(4)*params(12))^(-params(5));
    params(7)=ys_(6)*ys_(13)/ys_(5)^params(6);
    ys_(15)=1;
    ys_(16)=1;
    ys_(17)=1;
    ys_(18)=1;
    ys_(19)=1;
    % Auxiliary equations
    check_=0;
end
