function [ys_, params, info] = unemployment_RBC_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    params(25)=1.005;
    ys_(1)=1/params(1);
    params(26)=params(25)*ys_(1);
    params(27)=(params(14)-1)/params(14);
    ys_(10)=1;
    ys_(4)=.075;
    ys_(3)=1-ys_(4);
    ys_(7)=ys_(3)*((ys_(1)-(1-params(2)))/(params(27)*params(3)))^(1/(params(3)-1));
    ys_(6)=ys_(7)^params(3)*ys_(3)^(1-params(3));
    ys_(8)=params(2)*ys_(7);
    ys_(11)=ys_(3)*params(6)/ys_(4);
    params(11)=ys_(6)*0.01/(ys_(4)*ys_(11)^(1+params(8))/(1+params(8)));
    ys_(13)=params(11)*ys_(11)^params(8);
    ys_(12)=ys_(13)*params(12)/(1-params(12));
    ys_(5)=ys_(6)*params(27)*(1-params(3))/ys_(3)-ys_(13)+params(1)*ys_(13)*(1-params(6));
    ys_(2)=ys_(6)*(1-params(9))-ys_(8)-ys_(4)*ys_(11)^(1+params(8))*params(11)/(1+params(8));
    ys_(9)=ys_(2)^(-params(4));
    params(7)=ys_(9)*(ys_(5)*(1-params(13))-ys_(12)*(1-params(1)*(1-params(6))));
    params(10)=ys_(5)*params(13);
    ys_(14)=1;
    ys_(15)=1;
    ys_(16)=1;
    ys_(17)=1;
    ys_(18)=1;
    e_r=1;
    % Auxiliary equations
    check_=0;
end
